* Setup
  Make sure your Docker/docker-compose versions are up-to-date. To be safe, I'd try matching my version below.
  
  - Docker version: 19.03.13
  - Docker-compose version: 1.27.4

  The following aren't needed, since the project is containerized, however, I'm providing it in case any local development happens.
  - Gradle version: 6.6.1
  - Java version: 14.0

** Steps    
  - Create a *gradle.properties* file with your credentials (for GitHub API requests), replacing the words inside the brackets with your credentials. You can find out how to generate an API token here: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token.
    #+begin_src bash
      cd <project_dir>

      # This is your GitHub username
      echo "github_username=<username>" >> gradle.properties

      # This is your GitHub API token
      echo "github_token=<token>" >> gradle.properties"
    #+end_src
    
  - Run the Docker container (make sure you're using an updated version of Docker at least according to the specs I wrote above).     This will then run the container, which runs each of the three tasks. The result of this will be a newly created branch, an updated project name/version, and a new feature flag diff.
    #+begin_src bash
cd <project_dir>/docker

docker-compose up
    #+end_src

The resulting build, if successful, should look like the following (docker-compose up --build):

#+begin_example 
Building dev
Step 1/3 : FROM gradle:jdk14
 ---> cc5784080a16
Step 2/3 : WORKDIR /usr/slack_assessment
 ---> Using cache
 ---> 99fbc93d3bdb
Step 3/3 : ENTRYPOINT gradle codeFreeze
 ---> Using cache
 ---> df4d9e775868

Successfully built df4d9e775868
Successfully tagged docker_dev:latest
Recreating docker_dev_1 ... done
Attaching to docker_dev_1
dev_1  | Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
dev_1  | > Task :buildSrc:compileJava NO-SOURCE
dev_1  |
dev_1  | > Task :buildSrc:compileGroovy
dev_1  | WARNING: An illegal reflective access operation has occurred
dev_1  | WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/opt/gradle/lib/groovy-all-1.3-2.5.12.jar) to method java.util.AbstractCollection.finishToArray(java.lang.Object[],java.util.Iterator)
dev_1  | WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
dev_1  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
dev_1  | WARNING: All illegal access operations will be denied in a future release
dev_1  |
dev_1  | > Task :buildSrc:processResources NO-SOURCE
dev_1  | > Task :buildSrc:classes
dev_1  | > Task :buildSrc:jar
dev_1  | > Task :buildSrc:assemble
dev_1  | > Task :buildSrc:compileTestJava NO-SOURCE
dev_1  | > Task :buildSrc:compileTestGroovy NO-SOURCE
dev_1  | > Task :buildSrc:processTestResources NO-SOURCE
dev_1  | > Task :buildSrc:testClasses UP-TO-DATE
dev_1  | > Task :buildSrc:test NO-SOURCE
dev_1  | > Task :buildSrc:check UP-TO-DATE
dev_1  | > Task :buildSrc:build
dev_1  | > Task :codeFreeze UP-TO-DATE
dev_1  |
dev_1  | > Task :cutBranch
dev_1  | Checking if branch 'Cake/1.2' exists...
dev_1  | No remote branch found named 'Cake/1.2' due to invalid response: java.lang.Exception: Request returned with code 404: Not Found.
dev_1  | Attempting to retrieve ref from branch 'master'.
dev_1  | Request returned successfully with response code 200 and message 'OK'.
dev_1  | Successfully retrieved ref: 'd5f1349febf1981d6173a0a1ce4923d611d395a8'.
dev_1  | Attempting to create branch with name 'Cake/1.2' from 'master'.
dev_1  | Request returned successfully with response code 201 and message 'Created'.
dev_1  | Branch 'Cake/1.2' was successfully created.
dev_1  |
dev_1  | > Task :generateFFDiff
dev_1  | Attempting to diff current and previous feature flags.
dev_1  | Checking if branch 'Beer/1.1' exists...
dev_1  | No remote branch found named 'Beer/1.1' due to invalid response: java.lang.Exception: Request returned with code 404: Not Found.
dev_1  | Previous version's branch 'Beer/1.1' does not exist. The diff will only contain current branch's feature flag contents.
dev_1  |
dev_1  | > Task :updateReleaseVersion
dev_1  | Attempting to update release <name/version> from <Cake/1.2> to <Date/1.3>
dev_1  | Successfully updated release <name/version> from <Cake/1.2> to <Date/1.3>
dev_1  |
dev_1  | Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
dev_1  | Use '--warning-mode all' to show the individual deprecation warnings.
dev_1  | See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings
dev_1  |
dev_1  | BUILD SUCCESSFUL in 27s
dev_1  | 3 actionable tasks: 3 executed
docker_dev_1 exited with code 0
#+end_example

** Running Tasks
   In order to run a specific task, you can do either of the following:
  1. Docker only: You'll need to change the Dockerfile. On line 5 of *<project dir>/docker/Dockerfile/* you'll find the entrypoint command that executes when the container is run. Change it to which ever task you'd like to run and then rebuild the image like below. *Adding --stacktrace to the Gradle command will give you a stacktrace that will aid in debugging*

#+begin_src bash
cd <root dir>/docker

# You'll need to rebuild the image
docker-compose up --build
#+end_src

  2. Without Docker (you'll need Gradle, Java, etc to be able to run): You can run commands inside the Gradle project.
#+begin_src bash
cd <project dir>

# Replace task name with your desired task. Note the optional stacktrace flag.
./gradlew <task name> [--stacktrace]
#+end_src
* Troubleshooting
  - Make sure you have Docker installed.
  - Check the correct version of Docker is being used. See the versions that I'm using to make sure you're compatible.
  - Make sure Docker is running (this actually happens to me relatively frequently)
  - Make sure you have a functioning internet connection, since requests to GitHub are being made. You can curl -u<username:token> https://api.github.com/repos/SlackRecruiting/br-code-exercise-170536289/git/refs/heads/master or other GitHub API endpoints to see if it's the application or the server failing.
  - No credentials file was added, in which case requests to GitHub will fail with "HTTP 404: Not Found" errors.
  - *Adding --stacktrace to the Gradle command will give you a stacktrace that will aid in debugging*
* Architecture
** Directory Hierarchy  
  - The directory structure is designed in such a way that supports modification and extensibility. Additional plugins/tasks/utility classes can be added easily by creating a class and putting them into their respective directory.
  - The architecture of this project is designed to be a plug-and-play plugin that can be injected into any Gradle project.
  - The *buildSrc/* directory contains the plugin code (e.g. tasks that can be used by the main project, e.g. the parent directory of *buildSrc*). *buildSrc* is a Gradle-specific directory which is a self-contained Gradle project (with its own build.gradle which can download independent dependencies from the main project) that gets packaged as a .jar and put into the Java classpath. The main project can then import the classes (such as the Gradle tasks) from this .jar.

** Task classes
   Task classes contain a method annotated by *@TaskAction* which is the main task method that will be run when the task represented by this task is used. Each task has detailed print statements for when running on CI/CD, which aids in debugging when looking at the log statements.
   The following task classes are defined in *buildSrc/src/main/groovy/tasks/*:
  - CutBranchTask: This task class queries the current name and version and then creates a (remote) branch named "<release name>/<release version>". If a branch by that name already exists, then a task exception is thrown with a message saying that the branch already exists. Note that the new branch will be based off of "master", which is a field in the CutBranchTask that can be changed if the base branch needs to be changed.
  - GenerateFFDiffTask: This task class generates a diff between the (local) current branch's feature flag statuses and the previous branch's statuses. If the previous branch does not exist (e.g. when the current branch is the first one), then the current version's FF content will be the displayed as the contents of the diff file.
    
    The feature flag diff task will create a diff file in the same directory as FF.csv. Each record in the CSV will be the diff of the current and previous branch if it exists. If the following is the actual diff:
| Cake/1.2_name | Cake/1.2_version | Beer/1.1_name | Beer/1.1_version |
|---------------+------------------+---------------+------------------|
| FLAG_B        | OFF              | FLAG_B        | ON               |
| FLAG_C        | ON               | FLAG_C        | OFF              |

Then the resulting CSV will look like this:

    #+begin_src CSV
[Cake/1.2]_name,[Cake/1.2]_version,[Beer/1.1_name],[Beer/1.1]_version
Flag_B,OFF,Flag_B,ON
Flag_C,ON,Flag_C,OFF
    #+end_src
  
  - UpdateReleaseVersionTask: The task class will update the project's name and version to the next one. In case that the "releases.csv" file does not contain a next one (e.g. when the current version is the last), then a task exception will be thrown.

** Plugin classes    
  The task classes are then registered to the plugin in *buildSrc/src/main/groovy/plugins/CodeFreezePlugin.groovy*. This plugin is then registered as a plugin in the main project *build.gradle*.
  This means that the tasks are able to be used in the main project (e.g. someone can do 'gradle cutBranch' from parent directory).

** Utility classes
  There are also some utility classes (defined in *buildSrc/src/main/groovy/utils/*):
  - GitUtils: this class is a wrapper for Git related API requests.
  - ReleaseUtils: this class contains some methods for querying for release information from the provided .plist and .csv files.
  - Release: a class that represents a release with a name and version, previous name and version, and next name and version. This is useful to store the information so the information isn't queried many times.
